### PR TITLE
fix(payment): persist payment history on save/load (Fixes #116)

### LINKED ISSUE #116: Fix payment history

### PR DESCRIPTION
**Pull request by Yourface1746**
Fixes #116

### CODE REVIEW

File: src/main/java/seedu/address/logic/commands/PayCommand.java [hunk 1]
```diff
@@ -60,7 +60,7 @@ public CommandResult execute(Model model) throws CommandException {
         }
         Person personToAddPayment = lastShownList.get(index.getZeroBased());
 
-        if (personToAddPayment.getFinance().get().getOwedAmount().isZero()) {
+        if (personToAddPayment.getFinance().orElse(new Finance()).getOwedAmount().isZero()) {
```
Comment (samthambad) [inline src/main/java/seedu/address/logic/commands/PayCommand.java]: Good defensive programming

File: src/main/java/seedu/address/logic/commands/PayCommand.java [hunk 2]
```diff
@@ -84,7 +84,7 @@ public CommandResult execute(Model model) throws CommandException {
      * @throws java.util.NoSuchElementException if the person has no finance present.
      */
     public Finance updateFinance(Person p, FinanceAmount payment) {
-        Finance oldFinance = p.getFinance().get();
+        Finance oldFinance = p.getFinance().orElse(new Finance());
```
Comment (samthambad) [inline src/main/java/seedu/address/logic/commands/PayCommand.java]: Good defensive programming

File: src/test/java/seedu/address/storage/JsonAdaptedPaymentEntryTest.java [hunk 3]
```diff
@@ -0,0 +1,52 @@
...
+    @Test
+    public void toModelType_validFields_returnsPaymentEntry() throws Exception {
+        JsonAdaptedPaymentEntry json =
+                new JsonAdaptedPaymentEntry("2025-10-28", "12.34", "note");
+        PaymentEntry entry = json.toModelType();
+
+        assertEquals(LocalDate.parse("2025-10-28"), entry.getDate());
+        assertEquals(12.34, entry.getAmount().getAmount(), 1e-9);
+        assertEquals("note", entry.getNote());
+    }
```
Comment (samthambad) [inline src/test/java/seedu/address/storage/JsonAdaptedPaymentEntryTest.java]: Good usage of assertions

**Review by MoeySeanJean — APPROVED** [review]
LGTM
